apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: demo
        image: harbor.lanhaoyuan.top/demo/demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
